export default {
	HANDLE_GET_PATIENTS_SAGA: 'HANDLE_GET_PATIENTS_SAGA',
	HANDLE_GET_PATIENTS: 'HANDLE_GET_PATIENTS',
	HANDLE_CREATE_PATIENTS: 'HANDLE_CREATE_PATIENTS',
	HANDLE_CREATE_PATIENTS_ADDRESS: 'HANDLE_CREATE_PATIENTS_ADDRESS',
	HANDLE_CREATE_PATIENTS_SAGA: 'HANDLE_CREATE_PATIENTS_SAGA',
};