//Constants that get passed into patientActions

export default {
	HANDLE_GET_PATIENTS_SAGA: 'HANDLE_GET_PATIENTS_SAGA',
	HANDLE_GET_PATIENTS: 'HANDLE_GET_PATIENTS',
	HANDLE_CREATE_PATIENTS: 'HANDLE_CREATE_PATIENTS',
	HANDLE_CREATE_PATIENTS_ADDRESS: 'HANDLE_CREATE_PATIENTS_ADDRESS',
	HANDLE_EDIT_PATIENTS: 'HANDLE_EDIT_PATIENTS',
	HANDLE_EDIT_PATIENTS_ADDRESS: 'HANDLE_EDIT_PATIENTS_ADDRESS',
	HANDLE_CREATE_PATIENTS_SAGA: 'HANDLE_CREATE_PATIENTS_SAGA',
	HANDLE_CREATE_REDIRECT: 'HANDLE_CREATE_VIEW_REDIRECT',
	HANDLE_VIEW_REDIRECT: 'HANDLE_VIEW_REDIRECT',
	HANDLE_EDIT_REDIRECT: 'HANDLE_EDIT_REDIRECT',
	HANDLE_GET_SINGLE_PATIENT: 'HANDLE_GET_SINGLE_PATIENT',
	HANDLE_GET_SINGLE_PATIENT_SAGA: 'HANDLE_GET_SINGLE_PATIENT_SAGA',
	HANDLE_EDIT_SINGLE_PATIENT: 'HANDLE_EDIT_SINGLE_PATIENT',
	HANDLE_EDIT_SINGLE_PATIENT_SAGA: 'HANDLE_EDIT_SINGLE_PATIENT_SAGA',
	HANDLE_UPDATE_SINGLE_PATIENT_INFO: 'HANDLE_UPDATE_SINGLE_PATIENT_INFO',
	HANDLE_GET_SINGLE_PATIENT_ENCOUNTERS: 'HANDLE_GET_SINGLE_PATIENT_ENCOUNTERS',
	HANDLE_GET_SINGLE_PATIENT_ENCOUNTERS_SAGA: 'HANDLE_GET_SINGLE_PATIENT_ENCOUNTERS_SAGA',
	HANDLE_DELETE_SINGLE_PATIENT_SAGA: 'HANDLE_DELETE_SINGLE_PATIENT_SAGA',
};