export default {
	HANDLE_LOGIN: 'HANDLE_LOGIN',
	HANDLE_IS_LOGGED_IN: 'HANDLE_IS_LOGGED_IN',
	HANDLE_IS_LOGGED_OUT: 'HANDLE_IS_LOGGED_OUT',
	HANDLE_GET_USER_SAGA: 'HANDLE_GET_USER_SAGA',
	HANDLE_GET_USER: 'HANDLE_GET_USER',
	HANDLE_ERROR: 'HANDLE_ERROR',
	HANDLE_DECODEJWT: 'HANDLE_DECODEJWT',
};
